[package]
name = "rover"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
bytemuck = { version = "1.24.0", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.29"
nalgebra = "0.34.1"
pollster = "0.4.0"
wgpu = "27.0.1"
winit = "0.30.12"
